<?php
header('Access-Control-Allow-Origin: *');
/**
 * @return mixed
 */
function pertamina_core_menu() {
    $items['coremodule'] = array(
        'title' => 'Pertamina Core Module',
        'description' => 'Pertamina core module.',
        'page callback' => 'pertamina_ikhwan',
        'access arguments' => array('access pertamina core module'),
    );
    $items['graphtotalomset'] = array(
        'title' => 'Graphic Pendapatan Pertamina',
        'description' => 'Graphic total omset pertamina, Bulanan, Mingguan, Harian',
        'page callback' => 'ikhwan_chart_total_omset',
        'access arguments' => array('access pertamina core module'),
        'type' => MENU_CALLBACK,
    );
    $items['inputpenjualan'] = array(
        'title' => 'Input Penjualan Pertamina',
        'description' => 'Input penjualan pertamina',
        'page callback' => 'input_penjualan_pertamina',
        'access arguments' => array('access pertamina core module'),
        'type' => MENU_CALLBACK,
    );
    $items['laporanharian'] = array(
        'title' => 'Laporan Harian Penjualan Pom Bensin GISBH',
        'description' => 'Laporan harian penjualan pom bensin',
        'page callback' => 'create_laporan_penjualan_harian',
        'access arguments' => array('access pertamina core module'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * @return array
 */
function pertamina_core_permission() {
    return array(
        'access pertamina core module' => array(
            'title' => t('access pertamina'),
            'description' => t('enable to get access for pertamina core module.'),
        ),
        'access input data pertamina' => array(
            'title' => t('access input data pertamina'),
            'description' => t('enable to get access for input data pertamina.'),
        ),
    );
}

require_once 'ikhwan_core_function.api.php';
require_once 'pertamina_core.api.php';
require_once 'pertamina.chart.api.php';
require_once 'pertamina_form.api.php';

/**
 * @return string
 */
function pertamina_ikhwan(){
    return 'Pertamina Core Module';
}