<?php
/**
 * Implementation of hook_views_api().
*/
function view_function_views_api() {
  return array(
    'api' => 3.0,
  );  
}

function view_function_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'view_function'). '/views', '/.*\.view$/');
  $views = array();
  if (count($files)){
	  foreach ($files as $absolute => $file) {
	    require $absolute;
	    if (isset($view)) {
	      $views[$file->name] = $view;
	    }   
	  }
	}
  return $views;
}

function create_array_from_view($view_name, $args = null, $filter = null, $display_id = 'default'){
	$display_id = $display_id;
	$view_detail = views_get_view($view_name);
  $view_detail->set_display($display_id);
  if(count($filter)){
  	for ($i = 0;$i < count($filter);$i++){
	  	$item = $view_detail->get_item($display_id, 'filter', $filter[$i]['filtername']);
	  	$item['value'] = $filter[$i]['filtervalue']; 
	 		$view_detail->set_item($display_id, 'filter', $filter[$i]['filtername'], $item);
	 	}
  }
  if (count($args)){
  	$view_detail->set_arguments($args);
  }
  $view_detail->pre_execute();
	$view_detail->execute();
	return $view_detail->result;
}