<?php

/**
 * Implementation of hook_menu().
 */
function formtable_menu() {
  $items = array();

  // A page to demonstrate theming form elements in a table.
  $items['formtable'] = array(
    'title' => 'Form Table Example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formtable_form_table_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implementation of hook_theme.
 */
function formtable_theme() {
  return array(
    'formtable_form_table' => array(
      // The renderable element is the form.
      'render element' => 'form',
    ),
  );
}

/**
 * Page Callback / Form Builder for the table form.
 */
function formtable_form_table_form($form = array(), &$form_state) {
  $tableHeader = create_assignment_header();
  $tableRow = create_assignment_row();
  //dpm($tableRow);
  $form['table'] = array(
    // Theme this part of the form as a table.
    '#theme' => 'formtable_form_table',
    // Pass header information to the theme function.
    '#header' => $tableHeader,
    // Rows in the form table.
    'rows' => $tableRow,
  );

  // Add a submit button for fun.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Theme callback for the form table.
 */
function theme_formtable_form_table(&$variables) {
  // Get the userful values.
  $form = $variables['form'];
  $rows = $form['rows'];
  $header = $form['#header'];
  $footer = $form['#footer'];
	$attributes = $form['#attributes'];
  // Setup the structure to be rendered and returned.
  $content = array(
    '#theme' => 'table',
    '#header' => $header,
    '#footer' => $footer,
    '#rows' => array(),
    '#attributes' => $attributes,
  );
  // Traverse each row.  @see element_chidren().
  foreach (element_children($rows) as $row_index) {
    $row = array();
    // Traverse each column in the row.  @see element_children().
    $rowClass = 'old-row';
    foreach (element_children($rows[$row_index]) as $col_index) {
      // Render the column form element.
      $class = '';
      if (isset($rows[$row_index][$col_index]['#attributes']['outerclass'])){
      	$class = implode(' ',$rows[$row_index][$col_index]['#attributes']['outerclass']);
      	unset($rows[$row_index][$col_index]['#attributes']['outerclass']);
      }
      //unset($rows[$row_index][$col_index]['class']);
      $explodeIdx = explode('-',$col_index);
      if (in_array('new',$explodeIdx)){
        $rowClass = 'new-row';
      }
      $row[] = array('data' => drupal_render($rows[$row_index][$col_index]),'class' => $class);
    }
    // Add the row to the table.
    $content['#rows'][] = array('data' => $row, 'class' => $rowClass);
  }

  // Redner the table and return.
  return drupal_render($content);
}